import type { Metadata } from "next";
import Navbar from '@/components/Navbar';
import Offcanvas from '@/components/Offcanvas';
import MainContainer from '@/components/MainContainer';
import {UIProvider} from '@/context/ui';

import './globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:opsz,wght@14..32,279&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Quicksand:wght@300..700&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
      </head>
      <body>
        <UIProvider>
          <Navbar/>
          <Offcanvas/>
          <MainContainer>
            {children}
          </MainContainer>
        </UIProvider>
      </body>
    </html>
  );
}
